parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2018
  sourceType: 'module'
rules:
  '@typescript-eslint/no-unused-vars-experimental': 'error'
  '@typescript-eslint/explicit-function-return-type': 'error'
